CREATE DATABASE IF NOT EXISTS fatecservlets;
USE fatecservlets;

DROP TABLE IF EXISTS JOGOS;
DROP TABLE IF EXISTS DIFICULDADE;

CREATE TABLE JOGOS (
    NOME VARCHAR(100),
    DIFICULDADE VARCHAR(10)
);

CREATE TABLE DIFICULDADE (
    DIFICULDADE VARCHAR(10)
);

ALTER TABLE DIFICULDADE
ADD CONSTRAINT PKDIFICULDADE
PRIMARY KEY (DIFICULDADE);

ALTER TABLE JOGOS 
ADD CONSTRAINT FKDIFICULDADE
FOREIGN KEY (DIFICULDADE) REFERENCES DIFICULDADE(DIFICULDADE);

INSERT INTO DIFICULDADE VALUES ("Easy");

INSERT INTO DIFICULDADE VALUES ("Nice");

INSERT INTO DIFICULDADE VALUES ("Treta");

INSERT INTO JOGOS VALUES (
    "Earthbound", "Treta"
);