CREATE DATABASE IF NOT EXISTS fatecservlets;
USE fatecservlets;

DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE USUARIOS (
    USUARIO VARCHAR(20),
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(20),
    PASSWORD CHAR(32),
    PERFIL CHAR(20)
);

ALTER TABLE USUARIOS 
ADD CONSTRAINT PKUSUARIO 
PRIMARY KEY (USUARIO);