DROP DATABASE IF EXISTS fatecservlets;
CREATE DATABASE IF NOT EXISTS fatecservlets;
USE fatecservlets;

DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS NOTICIAS;

CREATE TABLE USUARIOS (
    USUARIO VARCHAR(20),
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(20),
    PASSWORD CHAR(32)
);

CREATE TABLE NOTICIAS (
    TIPO VARCHAR(20),
    JORNALISTA VARCHAR(20),
    TITULO VARCHAR(50),
    DESCRICAO VARCHAR(255),
    DATACRIACAO DATE,
    APROVADOR_ID VARCHAR(20),
    APROVADOR_DATA DATE,
    ASSINANTES INT
);

ALTER TABLE USUARIOS
ADD CONSTRAINT PKUSUARIOS
PRIMARY KEY (USUARIO);

ALTER TABLE NOTICIAS
ADD CONSTRAINT PKNOTICIAS
PRIMARY KEY (TITULO);

ALTER TABLE NOTICIAS 
ADD CONSTRAINT FKAPROVADOR
FOREIGN KEY (APROVADOR_ID) REFERENCES USUARIOS(USUARIO);

INSERT INTO USUARIOS VALUES (
    "john", "Johnny Newspaperseed", "johnny@springfieldshopper.com",
    "555-8628", "8B7564079340B755B2366E2C342485A5"
);

INSERT INTO NOTICIAS VALUES (
    "Gossip", "Johnny Newspaperseed", "Local man loses pants, life",
    "Beaver Rescue Falls Short", DATE("1995-11-19"), "john", DATE("1995-11-19"), 1
);